function [inpname,msxname,node,time,Q_load,formation,parameter1,parameter2,Pattern,bulk,tank,wall,bulkg,wallg,condition]=inputfile

filename ='parameters.txt'

fid = fopen(filename);
pf = textscan(fid,'%s%s%*[^\n]');
pf1 = pf{2}

inpname = pf1(1,1);
inpname = cell2mat(inpname)
msxname = pf1(1,1);
msxname = cell2mat(msxname)
node = pf1(2,1);
node = cell2mat(node);
node  = str2double(node);
time = pf1(4,1);
time  = cell2mat(time);
time  = str2double(time);
Q_load = pf1(5,1);
Q_load = cell2mat(Q_load);
Q_load = str2double(Q_load);
formation = pf1(6,1);
formation = cell2mat(formation);
parameter1 = pf1(7,1);
parameter1 = cell2mat(parameter1);
parameter1 = str2double(parameter1)
parameter2 = pf1(8,1);
parameter2 = cell2mat(parameter2);
parameter2 = str2double(parameter2)
Pattern = pf1(9,1);
Pattern = cell2mat(Pattern);
Pattern = str2double(Pattern);
bulk = pf1(10,1);
bulk = cell2mat(bulk);
bulk = str2double(bulk);
tank = pf1(11,1);
tank = cell2mat(tank);
tank = str2double(tank);
wall = pf1(12,1);
wall = cell2mat(wall);
wall = str2double(wall);
bulkg = pf1(13,1);
bulkg = cell2mat(bulkg);
bulkg = str2double(bulkg);
wallg = pf1(14,1);
wallg = cell2mat(wallg);
wallg = str2double(wallg);
condition = pf1(17,1);
condition = cell2mat(condition)